### ISSUE TITLE
Allow host OS upgrades to preserve config.json values after an upgrade

### ISSUE THREAD

**Issue by jviotti** [resin-os/resinhup#25]
We're recently seeing a recurrent use case of users looking forward to have a proxy between the device and Resin.io.

We're currently recommending them to edit `config.json` endpoint values to point to their proxy, however looks like endpoint values will be replaced on every host OS upgrades, which is very inconvenient.

A good "workaround" would be to only replace endpoints if they point to a known staging/production locations, but keep them as they are otherwise.

**Comment by imrehg** [comment]
Now there's way to set proxy properly, and the [supervisor](https://github.com/resin-io/resin-superviso) supports remote setting since v6.6.0, so that part should be covered.

I think for newer updates that replacement of values in `config.json` does not happen anymore anyways, so this should be probably good to close.
