### ISSUE TITLE
After update user container environment still contains the old version

### ISSUE THREAD

**Issue by agherzan** [resin-os/resinhup#35]
CC @shaunmulligan

**Comment by michal-mazurek** [comment]
@agherzan How could I recreate this? Running 'env' in the web terminal shows the updated version.

**Comment by agherzan** [comment]
@shaunmulligan might be able to help us a little with some details?

**Comment by shaunmulligan** [comment]
@agherzan is this the issue with the supervisor injecting the RESIN_HOST_VERSION into the users container? I think pablo might have fixed this in the supervisor so that it reads from os-release. If the env var shows the correct OS version in the user container after an update, then that is all we need. 

The main worry was that it would stay as the old hostos version, but it doesnt seem that is the case now.

**Comment by agherzan** [comment]
Cool. Based on this I'm closing the issue.
